spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/opsflow}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:opsflow}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:opsflow123}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

management.endpoints.web.exposure.include=health,info,metrics,prometheus

server.port=8081